<a href="https://colab.research.google.com/github/2023006766/deep-learning/blob/main/Matrix.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

print("MATRIX Operations")
print("="*70)

# Create matrices
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
B = np.array([[9, 8, 7], [6, 5, 4], [3, 2, 1]])
C = np.array([[1, 0], [0, 1]])  # Identity 2x2

print(f"\nMatrix A (3x3):\n{A}")
print(f"Matrix B (3x3):\n{B}")
print(f"Matrix C (2x2):\n{C}")

print("\nBasic Operations")
print("-"*50)
print(f"Addition: \n{A + B}")
print(f"Subtraction: \n{A - B}")
print(f"Element-wise: \n{A * B}")
print(f"Scalar multiplication: \n{2 * A}")

print("\nMatrix Multiplication")
print("-"*50)
print(f"A @ B (3x3):\n{np.matmul(A, B)}")
print(f"A @ A^T: \n{np.matmul(A, A.T)}")

print("\nTranspose")
print("-"*50)
print(f"A shape: {A.shape}")
print(f"A transpose shape: {A.T.shape}")
print(f"A^T:\n{A.T}")

print("\nDeterminant & Inverse")
print("-"*50)
det_C = np.linalg.det(C)
inv_C = np.linalg.inv(C)
print(f"Det(C): {det_C:.3f}")
print(f"Inv(C):\n{inv_C}")

print("\nMatrix Properties")
print("-"*50)
print(f"Rank(A): {np.linalg.matrix_rank(A)}")
print(f"Trace(A): {np.trace(A)}")
print(f"Norm(A): {np.linalg.norm(A):.2f}")

print("\nEigenvalues & Eigenvectors")
print("-"*50)
eigvals, eigvecs = np.linalg.eig(A)
print(f"Eigenvalues: {eigvals}")
print(f"Eigenvectors (first column):\n{eigvecs[:, 0]}")

print("\nSolve Linear System: Ax = b")
print("-"*50)
A = np.array([[2, 1, 0], [1, 3, 1], [0, 1, 4]])
b = np.array([1, 2, 3])
x = np.linalg.solve(A, b)
print(f"Solution x: {x}")

print("="*70)

MATRIX Operations

Matrix A (3x3):
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Matrix B (3x3):
[[9 8 7]
 [6 5 4]
 [3 2 1]]
Matrix C (2x2):
[[1 0]
 [0 1]]

Basic Operations
--------------------------------------------------
Addition: 
[[10 10 10]
 [10 10 10]
 [10 10 10]]
Subtraction: 
[[-8 -6 -4]
 [-2  0  2]
 [ 4  6  8]]
Element-wise: 
[[ 9 16 21]
 [24 25 24]
 [21 16  9]]
Scalar multiplication: 
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]

Matrix Multiplication
--------------------------------------------------
A @ B (3x3):
[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]
A @ A^T: 
[[ 14  32  50]
 [ 32  77 122]
 [ 50 122 194]]

Transpose
--------------------------------------------------
A shape: (3, 3)
A transpose shape: (3, 3)
A^T:
[[1 4 7]
 [2 5 8]
 [3 6 9]]

Determinant & Inverse
--------------------------------------------------
Det(C): 1.000
Inv(C):
[[1. 0.]
 [0. 1.]]

Matrix Properties
--------------------------------------------------
Rank(A): 2
Trace(A): 15
Norm(A): 16.88

Eigenvalues & Eigenvectors
---