<a href="https://colab.research.google.com/github/2023006766/deep-learning/blob/main/RNN_fixed_weights.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

def softmax(x):
    exp_x = np.exp(x - np.max(x))
    return exp_x / np.sum(exp_x)

def cross_entropy(y_true, y_pred):
    return -np.sum(y_true * np.log(y_pred + 1e-12))

# Weight matrices
Wxh = np.array([
[-1.753416, 0.9836007, 1.7042459822],
[-1.117427, 2.0291977, 0.5590203]
])

Whh = np.array([
[0.3323058, 1.704173],
[-0.4059835, 1.069699]
])

Why = np.array([
[5.0668307, 1.239699],
[-3.2882083, -2.307849]
])

# Biases
bh = np.array([
[-0.0238333],
[0.1707909]
])

by = np.array([
[0.03411441],
[-0.21828305]
])

# Inputs
x1 = np.array([[1],[0],[0]])
x2 = np.array([[0],[1],[0]])
x3 = np.array([[0],[0],[1]])

inputs = [x1, x2, x3]

# Targets
t1 = np.array([[0],[1]])
t2 = np.array([[1],[0]])
t3 = np.array([[0],[1]])

targets = [t1, t2, t3]

# Initial hidden state
h0 = np.array([[0],[0]])

hs = [h0]
ys = []
ps = []

loss = 0

for t in range(3):

    xt = inputs[t]

    wxhxt = Wxh @ xt
    print("wxhxt")
    print(wxhxt)

    whhhs = Whh @ hs[t]
    print("whhhs")
    print(whhhs)

    combined = wxhxt + whhhs + bh
    print("combined")
    print(combined)

    ht = np.tanh(combined)
    print("ht")
    print(ht)

    y = Why @ ht + by
    print("y")
    print(y)

    p = softmax(y)
    print("p")
    print(p)

    hs.append(ht)
    ys.append(y)
    ps.append(p)

    print("Current prediction (input):")
    print(xt)

    print("Next prediction (probabilities):")
    print(np.round(p,1))

    loss_entropy = cross_entropy(targets[t], p)
    print("loss-entropy")
    print(loss_entropy)

    loss += loss_entropy

print("Total Loss:", loss)

print("Hidden states:")
for i, h in enumerate(hs):
    print(f"h{i}:")
    print(h)

wxhxt
[[-1.753416]
 [-1.117427]]
whhhs
[[0.]
 [0.]]
combined
[[-1.7772493]
 [-0.9466361]]
ht
[[-0.94439854]
 [-0.73825635]]
y
[[-5.66620879]
 [ 4.59088026]]
p
[[3.51065037e-05]
 [9.99964893e-01]]
Current prediction (input):
[[1]
 [0]
 [0]]
Next prediction (probabilities):
[[0.]
 [1.]]
loss-entropy
3.510711891404759e-05
wxhxt
[[0.9836007]
 [2.0291977]]
whhhs
[[-1.57194565]
 [-0.40630185]]
combined
[[-0.61217825]
 [ 1.79368675]]
ht
[[-0.54565861]
 [ 0.9461483 ]]
y
[[-1.55770628]
 [-0.60761129]]
p
[[0.27886572]
 [0.72113428]]
Current prediction (input):
[[0]
 [1]
 [0]]
Next prediction (probabilities):
[[0.3]
 [0.7]]
loss-entropy
1.2770249035147625
wxhxt
[[1.70424598]
 [0.5590203 ]]
whhhs
[[1.43107487]
 [1.23362228]]
combined
[[3.11148755]
 [1.96343348]]
ht
[[0.99604118]
 [0.96135096]]
y
[[ 6.27267227]
 [-5.71212679]]
p
[[9.99993762e-01]
 [6.23828474e-06]]
Current prediction (input):
[[0]
 [0]
 [1]]
Next prediction (probabilities):
[[1.]
 [0.]]
loss-entropy
11.98480513450704
Total Loss: 13