<a href="https://colab.research.google.com/github/2023006766/deep-learning/blob/main/Working.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

print("Working with Arrays")
print("=" * 70)

arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

print(f"\nArray 1 (2x2):\n{arr1}")
print(f"Array 2 (2x2):\n{arr2}")

arr3 = np.arange(12).reshape(3, 4)
print(f"\nArray 3 (3x4):\n{arr3}")

print("\nArithmetic Operations")
print("-" * 50)
print(f"Addition:\n{arr1 + arr2}")
print(f"Subtraction:\n{arr1 - arr2}")
print(f"Multiplication:\n{arr1 * arr2}")
print(f"Division:\n{arr1 / arr2}")
print(f"Power:\n{arr1 ** 2}")

print("\nArray Properties")
print("-" * 50)
print(f"Shape arr1: {arr1.shape}")
print(f"Shape arr3: {arr3.shape}")
print(f"Dtype arr1: {arr1.dtype}")
print(f"Size arr1: {arr1.size}")
print(f"Dimensions arr1: {arr1.ndim}")

print("\nAggregate Functions")
print("-" * 50)
print(f"Sum: {np.sum(arr3)}")
print(f"Mean: {np.mean(arr3):.2f}")
print(f"Min / Max: {np.min(arr3)}, {np.max(arr3)}")
print(f"Standard Deviation: {np.std(arr3):.2f}")
print(f"Row sums: {np.sum(arr3, axis=1)}")
print(f"Column sums: {np.sum(arr3, axis=0)}")

print("\nArray Manipulation")
print("-" * 50)
print(f"Reshape (2x6):\n{np.arange(12).reshape(2, 6)}")
print(f"Flatten: {arr3.ravel()}")
print(f"Transpose:\n{arr3.T}")

print("\nUniversal Functions")
print("-" * 50)
print(f"Square Root:\n{np.sqrt(arr1)}")
print(f"Exponential (first row):\n{np.exp(arr1[:1])}")
print(f"Sine (arr3 values):\n{np.sin(arr3)}")

print("\nMatrix Operations")
print("-" * 50)
print(f"Dot product:\n{np.dot(arr1, arr2)}")
print(f"Matrix multiplication:\n{np.matmul(arr1, arr2)}")

print("\nStatistical Operations")
print("-" * 50)
print(f"Median: {np.median(arr3):.2f}")
print(f"25th Percentile: {np.percentile(arr3, 25):.2f}")

print("=" * 70)

Working with Arrays

Array 1 (2x2):
[[1 2]
 [3 4]]
Array 2 (2x2):
[[5 6]
 [7 8]]

Array 3 (3x4):
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

Arithmetic Operations
--------------------------------------------------
Addition:
[[ 6  8]
 [10 12]]
Subtraction:
[[-4 -4]
 [-4 -4]]
Multiplication:
[[ 5 12]
 [21 32]]
Division:
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
Power:
[[ 1  4]
 [ 9 16]]

Array Properties
--------------------------------------------------
Shape arr1: (2, 2)
Shape arr3: (3, 4)
Dtype arr1: int64
Size arr1: 4
Dimensions arr1: 2

Aggregate Functions
--------------------------------------------------
Sum: 66
Mean: 5.50
Min / Max: 0, 11
Standard Deviation: 3.45
Row sums: [ 6 22 38]
Column sums: [12 15 18 21]

Array Manipulation
--------------------------------------------------
Reshape (2x6):
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
Flatten: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Transpose:
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]

Universal Functions
-----