<a href="https://colab.research.google.com/github/2023006766/deep-learning/blob/main/xor_gate_random_initialization.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import matplotlib.pyplot as plt

# Network Architecture
input_size = 2
hidden_size = 2
output_size = 1

# Hyperparameters
learning_rate = 0.05
iterations = 50000
print_interval = 10000

# XOR Input and Target Output
X = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
y = np.array([[0], [1], [1], [0]])

# Random Initialization (Fixed seed for reproducibility)
np.random.seed(42)

w1 = np.random.uniform(-1, 1, (input_size, hidden_size))
w2 = np.random.uniform(-1, 1, (hidden_size, output_size))
b1 = np.zeros((1, hidden_size))
b2 = np.zeros((1, output_size))

print("Initial parameters:")
print("w1:\n", w1)
print("b1:\n", b1)

# Activation Functions
def sigmoid(z):
    return 1 / (1 + np.exp(-z))

def sigmoid_derivative(a):
    return a * (1 - a)

# Forward Propagation Function
def forward(x_input):
    z1 = np.dot(x_input, w1) + b1
    a1 = sigmoid(z1)
    z2 = np.dot(a1, w2) + b2
    a2 = sigmoid(z2)
    return a1, a2

# Training Loop
for i in range(iterations):
    # Forward Pass
    a1, output = forward(X)

    # Calculate Error
    error = y - output

    # Backpropagation
    d_output = error * sigmoid_derivative(output)
    d_hidden = np.dot(d_output, w2.T) * sigmoid_derivative(a1)

    # Weight and Bias Updates (Gradient Descent)
    w2 += learning_rate * np.dot(a1.T, d_output)
    b2 += learning_rate * np.sum(d_output, axis=0, keepdims=True)

    w1 += learning_rate * np.dot(X.T, d_hidden)
    b1 += learning_rate * np.sum(d_hidden, axis=0, keepdims=True)

    # Logging Loss
    if i % print_interval == 0:
        loss = np.mean(error ** 2)
        print(f"Iteration {i}, Loss: {loss}")

# Final Output after Training
print("\nFinal Output:")
final_output = forward(X)[1]
print(final_output)

Initial parameters:
w1:
 [[-0.25091976  0.90142861]
 [ 0.46398788  0.19731697]]
b1:
 [[0. 0.]]
Iteration 0, Loss: 0.2862998656081591
Iteration 10000, Loss: 0.24206911414262966
Iteration 20000, Loss: 0.009752333659208171
Iteration 30000, Loss: 0.0035049323253750772
Iteration 40000, Loss: 0.0020732302278657824

Final Output:
[[0.03684164]
 [0.95889122]
 [0.95891127]
 [0.03312025]]
